// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package marketplace

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/Khan/genqlient/graphql"
)

// GetPublishedModuleMyModuleMarketplaceModule includes the requested fields of the GraphQL type MarketplaceModule.
type GetPublishedModuleMyModuleMarketplaceModule struct {
	Title       string                                                                  `json:"title"`
	Description string                                                                  `json:"description"`
	Version     string                                                                  `json:"version"`
	Source      GetPublishedModuleMyModuleMarketplaceModuleSource                       `json:"-"`
	IconV2      GetPublishedModuleMyModuleMarketplaceModuleIconV2MarketplaceModuleImage `json:"iconV2"`
}

// GetTitle returns GetPublishedModuleMyModuleMarketplaceModule.Title, and is useful for accessing the field via an interface.
func (v *GetPublishedModuleMyModuleMarketplaceModule) GetTitle() string { return v.Title }

// GetDescription returns GetPublishedModuleMyModuleMarketplaceModule.Description, and is useful for accessing the field via an interface.
func (v *GetPublishedModuleMyModuleMarketplaceModule) GetDescription() string { return v.Description }

// GetVersion returns GetPublishedModuleMyModuleMarketplaceModule.Version, and is useful for accessing the field via an interface.
func (v *GetPublishedModuleMyModuleMarketplaceModule) GetVersion() string { return v.Version }

// GetSource returns GetPublishedModuleMyModuleMarketplaceModule.Source, and is useful for accessing the field via an interface.
func (v *GetPublishedModuleMyModuleMarketplaceModule) GetSource() GetPublishedModuleMyModuleMarketplaceModuleSource {
	return v.Source
}

// GetIconV2 returns GetPublishedModuleMyModuleMarketplaceModule.IconV2, and is useful for accessing the field via an interface.
func (v *GetPublishedModuleMyModuleMarketplaceModule) GetIconV2() GetPublishedModuleMyModuleMarketplaceModuleIconV2MarketplaceModuleImage {
	return v.IconV2
}

func (v *GetPublishedModuleMyModuleMarketplaceModule) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*GetPublishedModuleMyModuleMarketplaceModule
		Source json.RawMessage `json:"source"`
		graphql.NoUnmarshalJSON
	}
	firstPass.GetPublishedModuleMyModuleMarketplaceModule = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	{
		dst := &v.Source
		src := firstPass.Source
		if len(src) != 0 && string(src) != "null" {
			err = __unmarshalGetPublishedModuleMyModuleMarketplaceModuleSource(
				src, dst)
			if err != nil {
				return fmt.Errorf(
					"Unable to unmarshal GetPublishedModuleMyModuleMarketplaceModule.Source: %w", err)
			}
		}
	}
	return nil
}

type __premarshalGetPublishedModuleMyModuleMarketplaceModule struct {
	Title string `json:"title"`

	Description string `json:"description"`

	Version string `json:"version"`

	Source json.RawMessage `json:"source"`

	IconV2 GetPublishedModuleMyModuleMarketplaceModuleIconV2MarketplaceModuleImage `json:"iconV2"`
}

func (v *GetPublishedModuleMyModuleMarketplaceModule) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *GetPublishedModuleMyModuleMarketplaceModule) __premarshalJSON() (*__premarshalGetPublishedModuleMyModuleMarketplaceModule, error) {
	var retval __premarshalGetPublishedModuleMyModuleMarketplaceModule

	retval.Title = v.Title
	retval.Description = v.Description
	retval.Version = v.Version
	{

		dst := &retval.Source
		src := v.Source
		var err error
		*dst, err = __marshalGetPublishedModuleMyModuleMarketplaceModuleSource(
			&src)
		if err != nil {
			return nil, fmt.Errorf(
				"Unable to marshal GetPublishedModuleMyModuleMarketplaceModule.Source: %w", err)
		}
	}
	retval.IconV2 = v.IconV2
	return &retval, nil
}

// GetPublishedModuleMyModuleMarketplaceModuleIconV2MarketplaceModuleImage includes the requested fields of the GraphQL type MarketplaceModuleImage.
type GetPublishedModuleMyModuleMarketplaceModuleIconV2MarketplaceModuleImage struct {
	Url           string `json:"url"`
	FileName      string `json:"fileName"`
	FileExtension string `json:"fileExtension"`
}

// GetUrl returns GetPublishedModuleMyModuleMarketplaceModuleIconV2MarketplaceModuleImage.Url, and is useful for accessing the field via an interface.
func (v *GetPublishedModuleMyModuleMarketplaceModuleIconV2MarketplaceModuleImage) GetUrl() string {
	return v.Url
}

// GetFileName returns GetPublishedModuleMyModuleMarketplaceModuleIconV2MarketplaceModuleImage.FileName, and is useful for accessing the field via an interface.
func (v *GetPublishedModuleMyModuleMarketplaceModuleIconV2MarketplaceModuleImage) GetFileName() string {
	return v.FileName
}

// GetFileExtension returns GetPublishedModuleMyModuleMarketplaceModuleIconV2MarketplaceModuleImage.FileExtension, and is useful for accessing the field via an interface.
func (v *GetPublishedModuleMyModuleMarketplaceModuleIconV2MarketplaceModuleImage) GetFileExtension() string {
	return v.FileExtension
}

// GetPublishedModuleMyModuleMarketplaceModuleSource includes the requested fields of the GraphQL interface MarketplaceModuleSource.
//
// GetPublishedModuleMyModuleMarketplaceModuleSource is implemented by the following types:
// GetPublishedModuleMyModuleMarketplaceModuleSourceAppTile
// GetPublishedModuleMyModuleMarketplaceModuleSourceConsent
// GetPublishedModuleMyModuleMarketplaceModuleSourceDomainOntology
// GetPublishedModuleMyModuleMarketplaceModuleSourceInsightsLayout
// GetPublishedModuleMyModuleMarketplaceModuleSourceNotebook
// GetPublishedModuleMyModuleMarketplaceModuleSourceOcrReportExtractor
// GetPublishedModuleMyModuleMarketplaceModuleSourcePatientLayout
// GetPublishedModuleMyModuleMarketplaceModuleSourceProcessOntology
// GetPublishedModuleMyModuleMarketplaceModuleSourceProgramEnrollment
// GetPublishedModuleMyModuleMarketplaceModuleSourceProgramTemplate
// GetPublishedModuleMyModuleMarketplaceModuleSourceSearchLayout
// GetPublishedModuleMyModuleMarketplaceModuleSourceSurvey
// GetPublishedModuleMyModuleMarketplaceModuleSourceWellnessOffering
// GetPublishedModuleMyModuleMarketplaceModuleSourceWorkflow
type GetPublishedModuleMyModuleMarketplaceModuleSource interface {
	implementsGraphQLInterfaceGetPublishedModuleMyModuleMarketplaceModuleSource()
	// GetTypename returns the receiver's concrete GraphQL type-name (see interface doc for possible values).
	GetTypename() string
}

func (v *GetPublishedModuleMyModuleMarketplaceModuleSourceAppTile) implementsGraphQLInterfaceGetPublishedModuleMyModuleMarketplaceModuleSource() {
}
func (v *GetPublishedModuleMyModuleMarketplaceModuleSourceConsent) implementsGraphQLInterfaceGetPublishedModuleMyModuleMarketplaceModuleSource() {
}
func (v *GetPublishedModuleMyModuleMarketplaceModuleSourceDomainOntology) implementsGraphQLInterfaceGetPublishedModuleMyModuleMarketplaceModuleSource() {
}
func (v *GetPublishedModuleMyModuleMarketplaceModuleSourceInsightsLayout) implementsGraphQLInterfaceGetPublishedModuleMyModuleMarketplaceModuleSource() {
}
func (v *GetPublishedModuleMyModuleMarketplaceModuleSourceNotebook) implementsGraphQLInterfaceGetPublishedModuleMyModuleMarketplaceModuleSource() {
}
func (v *GetPublishedModuleMyModuleMarketplaceModuleSourceOcrReportExtractor) implementsGraphQLInterfaceGetPublishedModuleMyModuleMarketplaceModuleSource() {
}
func (v *GetPublishedModuleMyModuleMarketplaceModuleSourcePatientLayout) implementsGraphQLInterfaceGetPublishedModuleMyModuleMarketplaceModuleSource() {
}
func (v *GetPublishedModuleMyModuleMarketplaceModuleSourceProcessOntology) implementsGraphQLInterfaceGetPublishedModuleMyModuleMarketplaceModuleSource() {
}
func (v *GetPublishedModuleMyModuleMarketplaceModuleSourceProgramEnrollment) implementsGraphQLInterfaceGetPublishedModuleMyModuleMarketplaceModuleSource() {
}
func (v *GetPublishedModuleMyModuleMarketplaceModuleSourceProgramTemplate) implementsGraphQLInterfaceGetPublishedModuleMyModuleMarketplaceModuleSource() {
}
func (v *GetPublishedModuleMyModuleMarketplaceModuleSourceSearchLayout) implementsGraphQLInterfaceGetPublishedModuleMyModuleMarketplaceModuleSource() {
}
func (v *GetPublishedModuleMyModuleMarketplaceModuleSourceSurvey) implementsGraphQLInterfaceGetPublishedModuleMyModuleMarketplaceModuleSource() {
}
func (v *GetPublishedModuleMyModuleMarketplaceModuleSourceWellnessOffering) implementsGraphQLInterfaceGetPublishedModuleMyModuleMarketplaceModuleSource() {
}
func (v *GetPublishedModuleMyModuleMarketplaceModuleSourceWorkflow) implementsGraphQLInterfaceGetPublishedModuleMyModuleMarketplaceModuleSource() {
}

func __unmarshalGetPublishedModuleMyModuleMarketplaceModuleSource(b []byte, v *GetPublishedModuleMyModuleMarketplaceModuleSource) error {
	if string(b) == "null" {
		return nil
	}

	var tn struct {
		TypeName string `json:"__typename"`
	}
	err := json.Unmarshal(b, &tn)
	if err != nil {
		return err
	}

	switch tn.TypeName {
	case "AppTile":
		*v = new(GetPublishedModuleMyModuleMarketplaceModuleSourceAppTile)
		return json.Unmarshal(b, *v)
	case "Consent":
		*v = new(GetPublishedModuleMyModuleMarketplaceModuleSourceConsent)
		return json.Unmarshal(b, *v)
	case "DomainOntology":
		*v = new(GetPublishedModuleMyModuleMarketplaceModuleSourceDomainOntology)
		return json.Unmarshal(b, *v)
	case "InsightsLayout":
		*v = new(GetPublishedModuleMyModuleMarketplaceModuleSourceInsightsLayout)
		return json.Unmarshal(b, *v)
	case "Notebook":
		*v = new(GetPublishedModuleMyModuleMarketplaceModuleSourceNotebook)
		return json.Unmarshal(b, *v)
	case "OcrReportExtractor":
		*v = new(GetPublishedModuleMyModuleMarketplaceModuleSourceOcrReportExtractor)
		return json.Unmarshal(b, *v)
	case "PatientLayout":
		*v = new(GetPublishedModuleMyModuleMarketplaceModuleSourcePatientLayout)
		return json.Unmarshal(b, *v)
	case "ProcessOntology":
		*v = new(GetPublishedModuleMyModuleMarketplaceModuleSourceProcessOntology)
		return json.Unmarshal(b, *v)
	case "ProgramEnrollment":
		*v = new(GetPublishedModuleMyModuleMarketplaceModuleSourceProgramEnrollment)
		return json.Unmarshal(b, *v)
	case "ProgramTemplate":
		*v = new(GetPublishedModuleMyModuleMarketplaceModuleSourceProgramTemplate)
		return json.Unmarshal(b, *v)
	case "SearchLayout":
		*v = new(GetPublishedModuleMyModuleMarketplaceModuleSourceSearchLayout)
		return json.Unmarshal(b, *v)
	case "Survey":
		*v = new(GetPublishedModuleMyModuleMarketplaceModuleSourceSurvey)
		return json.Unmarshal(b, *v)
	case "WellnessOffering":
		*v = new(GetPublishedModuleMyModuleMarketplaceModuleSourceWellnessOffering)
		return json.Unmarshal(b, *v)
	case "Workflow":
		*v = new(GetPublishedModuleMyModuleMarketplaceModuleSourceWorkflow)
		return json.Unmarshal(b, *v)
	case "":
		return fmt.Errorf(
			"response was missing MarketplaceModuleSource.__typename")
	default:
		return fmt.Errorf(
			`unexpected concrete type for GetPublishedModuleMyModuleMarketplaceModuleSource: "%v"`, tn.TypeName)
	}
}

func __marshalGetPublishedModuleMyModuleMarketplaceModuleSource(v *GetPublishedModuleMyModuleMarketplaceModuleSource) ([]byte, error) {

	var typename string
	switch v := (*v).(type) {
	case *GetPublishedModuleMyModuleMarketplaceModuleSourceAppTile:
		typename = "AppTile"

		result := struct {
			TypeName string `json:"__typename"`
			*GetPublishedModuleMyModuleMarketplaceModuleSourceAppTile
		}{typename, v}
		return json.Marshal(result)
	case *GetPublishedModuleMyModuleMarketplaceModuleSourceConsent:
		typename = "Consent"

		result := struct {
			TypeName string `json:"__typename"`
			*GetPublishedModuleMyModuleMarketplaceModuleSourceConsent
		}{typename, v}
		return json.Marshal(result)
	case *GetPublishedModuleMyModuleMarketplaceModuleSourceDomainOntology:
		typename = "DomainOntology"

		result := struct {
			TypeName string `json:"__typename"`
			*GetPublishedModuleMyModuleMarketplaceModuleSourceDomainOntology
		}{typename, v}
		return json.Marshal(result)
	case *GetPublishedModuleMyModuleMarketplaceModuleSourceInsightsLayout:
		typename = "InsightsLayout"

		result := struct {
			TypeName string `json:"__typename"`
			*GetPublishedModuleMyModuleMarketplaceModuleSourceInsightsLayout
		}{typename, v}
		return json.Marshal(result)
	case *GetPublishedModuleMyModuleMarketplaceModuleSourceNotebook:
		typename = "Notebook"

		result := struct {
			TypeName string `json:"__typename"`
			*GetPublishedModuleMyModuleMarketplaceModuleSourceNotebook
		}{typename, v}
		return json.Marshal(result)
	case *GetPublishedModuleMyModuleMarketplaceModuleSourceOcrReportExtractor:
		typename = "OcrReportExtractor"

		result := struct {
			TypeName string `json:"__typename"`
			*GetPublishedModuleMyModuleMarketplaceModuleSourceOcrReportExtractor
		}{typename, v}
		return json.Marshal(result)
	case *GetPublishedModuleMyModuleMarketplaceModuleSourcePatientLayout:
		typename = "PatientLayout"

		result := struct {
			TypeName string `json:"__typename"`
			*GetPublishedModuleMyModuleMarketplaceModuleSourcePatientLayout
		}{typename, v}
		return json.Marshal(result)
	case *GetPublishedModuleMyModuleMarketplaceModuleSourceProcessOntology:
		typename = "ProcessOntology"

		result := struct {
			TypeName string `json:"__typename"`
			*GetPublishedModuleMyModuleMarketplaceModuleSourceProcessOntology
		}{typename, v}
		return json.Marshal(result)
	case *GetPublishedModuleMyModuleMarketplaceModuleSourceProgramEnrollment:
		typename = "ProgramEnrollment"

		result := struct {
			TypeName string `json:"__typename"`
			*GetPublishedModuleMyModuleMarketplaceModuleSourceProgramEnrollment
		}{typename, v}
		return json.Marshal(result)
	case *GetPublishedModuleMyModuleMarketplaceModuleSourceProgramTemplate:
		typename = "ProgramTemplate"

		result := struct {
			TypeName string `json:"__typename"`
			*GetPublishedModuleMyModuleMarketplaceModuleSourceProgramTemplate
		}{typename, v}
		return json.Marshal(result)
	case *GetPublishedModuleMyModuleMarketplaceModuleSourceSearchLayout:
		typename = "SearchLayout"

		result := struct {
			TypeName string `json:"__typename"`
			*GetPublishedModuleMyModuleMarketplaceModuleSourceSearchLayout
		}{typename, v}
		return json.Marshal(result)
	case *GetPublishedModuleMyModuleMarketplaceModuleSourceSurvey:
		typename = "Survey"

		result := struct {
			TypeName string `json:"__typename"`
			*GetPublishedModuleMyModuleMarketplaceModuleSourceSurvey
		}{typename, v}
		return json.Marshal(result)
	case *GetPublishedModuleMyModuleMarketplaceModuleSourceWellnessOffering:
		typename = "WellnessOffering"

		result := struct {
			TypeName string `json:"__typename"`
			*GetPublishedModuleMyModuleMarketplaceModuleSourceWellnessOffering
		}{typename, v}
		return json.Marshal(result)
	case *GetPublishedModuleMyModuleMarketplaceModuleSourceWorkflow:
		typename = "Workflow"

		result := struct {
			TypeName string `json:"__typename"`
			*GetPublishedModuleMyModuleMarketplaceModuleSourceWorkflow
		}{typename, v}
		return json.Marshal(result)
	case nil:
		return []byte("null"), nil
	default:
		return nil, fmt.Errorf(
			`unexpected concrete type for GetPublishedModuleMyModuleMarketplaceModuleSource: "%T"`, v)
	}
}

// GetPublishedModuleMyModuleMarketplaceModuleSourceAppTile includes the requested fields of the GraphQL type AppTile.
type GetPublishedModuleMyModuleMarketplaceModuleSourceAppTile struct {
	Typename string `json:"__typename"`
	Id       string `json:"id"`
}

// GetTypename returns GetPublishedModuleMyModuleMarketplaceModuleSourceAppTile.Typename, and is useful for accessing the field via an interface.
func (v *GetPublishedModuleMyModuleMarketplaceModuleSourceAppTile) GetTypename() string {
	return v.Typename
}

// GetId returns GetPublishedModuleMyModuleMarketplaceModuleSourceAppTile.Id, and is useful for accessing the field via an interface.
func (v *GetPublishedModuleMyModuleMarketplaceModuleSourceAppTile) GetId() string { return v.Id }

// GetPublishedModuleMyModuleMarketplaceModuleSourceConsent includes the requested fields of the GraphQL type Consent.
type GetPublishedModuleMyModuleMarketplaceModuleSourceConsent struct {
	Typename string `json:"__typename"`
}

// GetTypename returns GetPublishedModuleMyModuleMarketplaceModuleSourceConsent.Typename, and is useful for accessing the field via an interface.
func (v *GetPublishedModuleMyModuleMarketplaceModuleSourceConsent) GetTypename() string {
	return v.Typename
}

// GetPublishedModuleMyModuleMarketplaceModuleSourceDomainOntology includes the requested fields of the GraphQL type DomainOntology.
type GetPublishedModuleMyModuleMarketplaceModuleSourceDomainOntology struct {
	Typename string `json:"__typename"`
}

// GetTypename returns GetPublishedModuleMyModuleMarketplaceModuleSourceDomainOntology.Typename, and is useful for accessing the field via an interface.
func (v *GetPublishedModuleMyModuleMarketplaceModuleSourceDomainOntology) GetTypename() string {
	return v.Typename
}

// GetPublishedModuleMyModuleMarketplaceModuleSourceInsightsLayout includes the requested fields of the GraphQL type InsightsLayout.
type GetPublishedModuleMyModuleMarketplaceModuleSourceInsightsLayout struct {
	Typename string `json:"__typename"`
}

// GetTypename returns GetPublishedModuleMyModuleMarketplaceModuleSourceInsightsLayout.Typename, and is useful for accessing the field via an interface.
func (v *GetPublishedModuleMyModuleMarketplaceModuleSourceInsightsLayout) GetTypename() string {
	return v.Typename
}

// GetPublishedModuleMyModuleMarketplaceModuleSourceNotebook includes the requested fields of the GraphQL type Notebook.
type GetPublishedModuleMyModuleMarketplaceModuleSourceNotebook struct {
	Typename string `json:"__typename"`
}

// GetTypename returns GetPublishedModuleMyModuleMarketplaceModuleSourceNotebook.Typename, and is useful for accessing the field via an interface.
func (v *GetPublishedModuleMyModuleMarketplaceModuleSourceNotebook) GetTypename() string {
	return v.Typename
}

// GetPublishedModuleMyModuleMarketplaceModuleSourceOcrReportExtractor includes the requested fields of the GraphQL type OcrReportExtractor.
type GetPublishedModuleMyModuleMarketplaceModuleSourceOcrReportExtractor struct {
	Typename string `json:"__typename"`
}

// GetTypename returns GetPublishedModuleMyModuleMarketplaceModuleSourceOcrReportExtractor.Typename, and is useful for accessing the field via an interface.
func (v *GetPublishedModuleMyModuleMarketplaceModuleSourceOcrReportExtractor) GetTypename() string {
	return v.Typename
}

// GetPublishedModuleMyModuleMarketplaceModuleSourcePatientLayout includes the requested fields of the GraphQL type PatientLayout.
type GetPublishedModuleMyModuleMarketplaceModuleSourcePatientLayout struct {
	Typename string `json:"__typename"`
}

// GetTypename returns GetPublishedModuleMyModuleMarketplaceModuleSourcePatientLayout.Typename, and is useful for accessing the field via an interface.
func (v *GetPublishedModuleMyModuleMarketplaceModuleSourcePatientLayout) GetTypename() string {
	return v.Typename
}

// GetPublishedModuleMyModuleMarketplaceModuleSourceProcessOntology includes the requested fields of the GraphQL type ProcessOntology.
type GetPublishedModuleMyModuleMarketplaceModuleSourceProcessOntology struct {
	Typename string `json:"__typename"`
}

// GetTypename returns GetPublishedModuleMyModuleMarketplaceModuleSourceProcessOntology.Typename, and is useful for accessing the field via an interface.
func (v *GetPublishedModuleMyModuleMarketplaceModuleSourceProcessOntology) GetTypename() string {
	return v.Typename
}

// GetPublishedModuleMyModuleMarketplaceModuleSourceProgramEnrollment includes the requested fields of the GraphQL type ProgramEnrollment.
type GetPublishedModuleMyModuleMarketplaceModuleSourceProgramEnrollment struct {
	Typename string `json:"__typename"`
}

// GetTypename returns GetPublishedModuleMyModuleMarketplaceModuleSourceProgramEnrollment.Typename, and is useful for accessing the field via an interface.
func (v *GetPublishedModuleMyModuleMarketplaceModuleSourceProgramEnrollment) GetTypename() string {
	return v.Typename
}

// GetPublishedModuleMyModuleMarketplaceModuleSourceProgramTemplate includes the requested fields of the GraphQL type ProgramTemplate.
type GetPublishedModuleMyModuleMarketplaceModuleSourceProgramTemplate struct {
	Typename string `json:"__typename"`
}

// GetTypename returns GetPublishedModuleMyModuleMarketplaceModuleSourceProgramTemplate.Typename, and is useful for accessing the field via an interface.
func (v *GetPublishedModuleMyModuleMarketplaceModuleSourceProgramTemplate) GetTypename() string {
	return v.Typename
}

// GetPublishedModuleMyModuleMarketplaceModuleSourceSearchLayout includes the requested fields of the GraphQL type SearchLayout.
type GetPublishedModuleMyModuleMarketplaceModuleSourceSearchLayout struct {
	Typename string `json:"__typename"`
}

// GetTypename returns GetPublishedModuleMyModuleMarketplaceModuleSourceSearchLayout.Typename, and is useful for accessing the field via an interface.
func (v *GetPublishedModuleMyModuleMarketplaceModuleSourceSearchLayout) GetTypename() string {
	return v.Typename
}

// GetPublishedModuleMyModuleMarketplaceModuleSourceSurvey includes the requested fields of the GraphQL type Survey.
type GetPublishedModuleMyModuleMarketplaceModuleSourceSurvey struct {
	Typename string `json:"__typename"`
}

// GetTypename returns GetPublishedModuleMyModuleMarketplaceModuleSourceSurvey.Typename, and is useful for accessing the field via an interface.
func (v *GetPublishedModuleMyModuleMarketplaceModuleSourceSurvey) GetTypename() string {
	return v.Typename
}

// GetPublishedModuleMyModuleMarketplaceModuleSourceWellnessOffering includes the requested fields of the GraphQL type WellnessOffering.
type GetPublishedModuleMyModuleMarketplaceModuleSourceWellnessOffering struct {
	Typename string `json:"__typename"`
}

// GetTypename returns GetPublishedModuleMyModuleMarketplaceModuleSourceWellnessOffering.Typename, and is useful for accessing the field via an interface.
func (v *GetPublishedModuleMyModuleMarketplaceModuleSourceWellnessOffering) GetTypename() string {
	return v.Typename
}

// GetPublishedModuleMyModuleMarketplaceModuleSourceWorkflow includes the requested fields of the GraphQL type Workflow.
type GetPublishedModuleMyModuleMarketplaceModuleSourceWorkflow struct {
	Typename string `json:"__typename"`
}

// GetTypename returns GetPublishedModuleMyModuleMarketplaceModuleSourceWorkflow.Typename, and is useful for accessing the field via an interface.
func (v *GetPublishedModuleMyModuleMarketplaceModuleSourceWorkflow) GetTypename() string {
	return v.Typename
}

// GetPublishedModuleResponse is returned by GetPublishedModule on success.
type GetPublishedModuleResponse struct {
	MyModule GetPublishedModuleMyModuleMarketplaceModule `json:"myModule"`
}

// GetMyModule returns GetPublishedModuleResponse.MyModule, and is useful for accessing the field via an interface.
func (v *GetPublishedModuleResponse) GetMyModule() GetPublishedModuleMyModuleMarketplaceModule {
	return v.MyModule
}

// __GetPublishedModuleInput is used internally by genqlient
type __GetPublishedModuleInput struct {
	Id      string `json:"id"`
	Version string `json:"version"`
}

// GetId returns __GetPublishedModuleInput.Id, and is useful for accessing the field via an interface.
func (v *__GetPublishedModuleInput) GetId() string { return v.Id }

// GetVersion returns __GetPublishedModuleInput.Version, and is useful for accessing the field via an interface.
func (v *__GetPublishedModuleInput) GetVersion() string { return v.Version }

func GetPublishedModule(
	ctx context.Context,
	client graphql.Client,
	id string,
	version string,
) (*GetPublishedModuleResponse, error) {
	req := &graphql.Request{
		OpName: "GetPublishedModule",
		Query: `
query GetPublishedModule ($id: ID!, $version: String) {
	myModule(moduleId: $id, version: $version) {
		title
		description
		version
		source {
			__typename
			... on AppTile {
				id
			}
		}
		iconV2 {
			url
			fileName
			fileExtension
		}
	}
}
`,
		Variables: &__GetPublishedModuleInput{
			Id:      id,
			Version: version,
		},
	}
	var err error

	var data GetPublishedModuleResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}
